name: Rust

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy
      run: cargo clippy -- -D warnings
    - name: Format Check
      run: cargo fmt --all -- --check
    - name: Run Tests
      run: cargo test --verbose
